import '../globals.css'

import type { Metadata } from 'next'
import Providers from '@/components/layout/providers'

import { SidebarProvider } from '@/components/shadcn/sidebar'
import { Poppins, Raleway } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

const raleway = Raleway({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} flex overflow-y-hidden h-screen min-w-[650px]`}
      >
        <SidebarProvider>
          <main className="flex-1 flex h-full">
            <div className={`bg-primary flex-1 ${raleway.className} relative`}>
              <h2 className="text-white font-bold p-8">Socifit</h2>

              <div className="text-white absolute top-1/4 flex flex-col p-8 gap-4">
                <h1 className="max-w-[496px] text-2xl md:text-3xl lg:text-5xl">
                  Simplifique a Gestão da Sua Academia
                </h1>
                <h2 className="font-normal max-w-96 text-lg sm:text-xl lg:text-2xl">
                  Desde o cadastro de clientes até o agendamento de aulas, tudo
                  em um só lugar.
                </h2>
              </div>
            </div>
            <Providers>
              <div className="h-screen flex-1">{children}</div>
            </Providers>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
